#!/usr/bin/env python3
"""Prototype: deterministic extraction from ICORE 2026-round submission PDFs.

These documents are generated by the ICORE submission system via LaTeX, so
labels are stable and no LLM is needed for the structured fields. Every value
carries page + verbatim snippet provenance, validated against the
DocumentExtraction schema from SPEC.md §6.4.

Decision-document field capture (outcome / outcome_verbatim) is best-effort:
unlike the Data-document layout, no real Decision PDF has been inspected to
verify its structure, so those fields stay unverified low-confidence guesses.
"""
import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Literal, Optional

from pydantic import BaseModel, ValidationError, model_validator

# ---------- text loading ----------

MIN_TEXT_CHARS = 200


def load_pages(pdf_path):
    """Return list of page texts, dehyphenated and soft-wrapped."""
    if shutil.which("pdftotext") is None:
        raise RuntimeError(
            "pdftotext not found on PATH (install poppler-utils)")
    try:
        raw = subprocess.run(
            ["pdftotext", "-layout", str(pdf_path), "-"],
            capture_output=True, text=True, check=True).stdout
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            f"pdftotext failed on {pdf_path}: {exc.stderr.strip()}") from exc
    pages = raw.split("\f")
    out = []
    for p in pages:
        # join words broken across lines by LaTeX hyphenation
        p = re.sub(r"(\w)-\n(\w)", r"\1\2", p)
        out.append(p)
    return out


def find_page(pages, needle):
    for i, p in enumerate(pages, start=1):
        if needle in p:
            return i
    return None


# ---------- schema (SPEC.md §6.4 DocumentExtraction) ----------

class Provenance(BaseModel):
    page: int
    snippet: str
    confidence: Literal["high", "medium", "low"]
    method: Literal["regex", "table", "llm", "manual"]


class AreaLeader(BaseModel):
    name: str
    gs_hindex: int


class Instance(BaseModel):
    slot: str
    year: Optional[int] = None
    location: Optional[str] = None
    papers_submitted: Optional[int] = None
    papers_published: Optional[int] = None
    acceptance_rate_pct: Optional[int] = None


class Comparator(BaseModel):
    acronym: str
    claimed_rank: Optional[str] = None
    claimed_h5: Optional[int] = None


class Argument(BaseModel):
    claim_type: str
    summary: str
    page: int
    snippet: str


# Identity/context fields come from the crawl, not the document text, so the
# provenance invariant below doesn't apply to them.
_IDENTITY_FIELDS = {"core_id", "round", "link_type", "doc_url"}
# Populated only by the LLM argument-coding pass (SPEC.md §6.4 rule 2),
# not by this deterministic extractor.
_NOT_YET_POPULATED = {"comparators", "arguments"}


class DocumentExtraction(BaseModel):
    core_id: Optional[str] = None
    round: Optional[str] = None
    link_type: Optional[Literal["data", "decision"]] = None
    doc_url: Optional[str] = None

    current_rank: Optional[str] = None
    requested_rank: Optional[str] = None
    outcome: Optional[str] = None
    outcome_verbatim: Optional[str] = None

    for_codes: list[int] = []
    citation_data_source: Optional[str] = None
    centile_years: list[int] = []
    citation_top25_venue_pct: Optional[int] = None
    citation_top25_tier_baseline_pct: Optional[dict[str, int]] = None
    author_strength_top25_venue_pct: Optional[int] = None
    author_strength_top25_tier_baseline_pct: Optional[dict[str, int]] = None

    gs_h5_index: Optional[int] = None
    gs_h5_of_20th_in_category: Optional[int] = None
    gs_position_in_subcategory: Optional[str] = None
    gs_subcategory_url: Optional[str] = None

    pc_size: Optional[int] = None
    pc_established_count: Optional[int] = None
    pc_median_hindex: Optional[float] = None
    pc_top3_venues: Optional[str] = None
    wpp_position_pc: Optional[int] = None

    leaders_selection_method: Optional[str] = None
    area_leaders: list[AreaLeader] = []
    leaders_top3_venues: Optional[str] = None
    wpp_position_leaders: Optional[int] = None

    last_instances: list[Instance] = []
    submissions_by_year: list[int] = []
    acceptance_rates_pct: list[int] = []
    chair_hindex_by_year: list[int] = []

    icore_artifact_urls: list[str] = []

    relationship_to_similar_conferences: Optional[str] = None
    flagship_area_claim: Optional[str] = None
    other_relevant_info: Optional[str] = None

    comparators: list[Comparator] = []
    arguments: list[Argument] = []

    provenance: dict[str, Provenance] = {}

    @model_validator(mode="after")
    def _every_populated_field_has_provenance(self):
        missing = []
        for name in type(self).model_fields:
            if name in _IDENTITY_FIELDS or name in _NOT_YET_POPULATED:
                continue
            if name == "provenance":
                continue
            value = getattr(self, name)
            if value is None:
                continue
            if isinstance(value, (list, dict)) and len(value) == 0:
                continue
            if name not in self.provenance:
                missing.append(name)
        if missing:
            raise ValueError(
                "populated fields with no provenance (must be dropped, "
                f"not guessed): {missing}")
        return self


# ---------- provenance-carrying field capture ----------

class Extractor:
    def __init__(self, pages):
        self.pages = pages
        self.full = "\n".join(pages)
        # a flowed version: single-newlines inside a paragraph become spaces
        self.flowed = re.sub(r"(?<![\n:])\n(?![\n A-Z])", " ", self.full)
        self.fields = {}
        self.provenance = {}
        self.dropped = []

    def _record(self, key, value, snippet, method, confidence="high"):
        if value is None:
            return None
        page = find_page(self.pages, snippet.split("\n")[0][:60])
        if page is None:
            # Spec: a value with no page-level provenance is invalid and
            # must be dropped, not guessed. Drop loudly, don't keep it.
            self.dropped.append(key)
            return None
        self.fields[key] = value
        self.provenance[key] = {
            "page": page,
            "snippet": snippet.strip()[:200],
            "confidence": confidence,
            "method": method,
        }
        return value

    def label(self, key, label, cast=str, source=None):
        """Capture a `Label: value` line."""
        text = source if source is not None else self.full
        m = re.search(rf"^\s*{re.escape(label)}\s*:\s*(.+?)\s*$", text, re.M)
        if not m:
            return None
        try:
            val = cast(m.group(1).strip())
        except ValueError:
            return None
        return self._record(key, val, m.group(0), "regex")

    def pattern(self, key, rx, cast=str, group=1, confidence="high"):
        m = re.search(rx, self.flowed, re.M | re.S)
        if not m:
            return None
        try:
            val = cast(m.group(group).strip())
        except ValueError:
            return None
        return self._record(key, val, m.group(0), "regex", confidence)

    def section(self, key, start, end, confidence="high"):
        """Capture free text between two known headings."""
        m = re.search(rf"^{re.escape(start)}\s*\n(.*?)(?=^{end})",
                      self.full, re.M | re.S)
        if not m:
            return None
        body = re.sub(r"\s*\n\s*", " ", m.group(1)).strip()
        body = re.sub(r"\s{2,}", " ", body)
        if not body:
            return None
        # This is still a plain regex match against known heading text, not
        # a distinct capture method — keep it in the schema's method vocabulary.
        return self._record(key, body, m.group(0)[:200], "regex", confidence)


def pct_list(s):
    return [int(x) for x in re.findall(r"(\d+)\s*%", s)]


def int_list(s):
    return [int(x) for x in re.findall(r"\d+", s)]


# ---------- the extraction ----------

def extract(pdf_path, core_id=None, round_=None, link_type=None, doc_url=None):
    pages = load_pages(pdf_path)
    total_chars = sum(len(p) for p in pages)
    if total_chars < MIN_TEXT_CHARS:
        return {
            "source_pdf": Path(pdf_path).name,
            "pages": len(pages),
            "needs_ocr": True,
            "fields": {},
            "extra_fields": {},
            "dropped_fields": [],
            "provenance": {},
        }

    e = Extractor(pages)

    # --- header / initial details ---
    # Not part of the DocumentExtraction schema, but genuinely useful, so
    # they're kept separately rather than either discarded or smuggled into
    # the validated schema fields.
    extra = {}
    extra["title"] = e.label("title", "Title")
    extra["on_review_list"] = e.pattern(
        "on_review_list", r"(THIS CONFERENCE IS ON THE REVIEW LIST)",
        cast=lambda s: True)
    extra["papers_published_recent"] = e.pattern(
        "papers_published_recent",
        r"Size in terms of full published research papers.*?:\s*([\d, ]+)",
        cast=int_list)
    extra["attendees_band"] = e.label(
        "attendees_band", "Estimated number of attendees")
    extra = {k: v for k, v in extra.items() if v is not None}

    e.pattern("acronym", r"^Acronym\s*:\s*(\S+)")
    e.label("current_rank", "Rank")
    e.label("requested_rank", "Requested Rank")
    e.pattern("acceptance_rates_pct",
              r"Acceptance rates \(most recent first\):\s*([\d%, ]+)",
              cast=pct_list)
    e.pattern("submissions_by_year",
              r"Number of submitted papers each year \(most recent first\)\s*([\d, ]+)",
              cast=int_list)
    e.pattern("chair_hindex_by_year",
              r"H-index of highest ranked program/general chair each year \(most recent first\)\s*([\d, ]+)",
              cast=int_list)

    # --- ICORE-computed impact, incl. the FoR tier baselines ---
    e.pattern("for_codes",
              r"percentage of papers in each rank within.*?Field of Research code\(s\)\s*([\d, ]+)\.",
              cast=int_list)
    e.pattern("citation_data_source",
              r"Information contained within these graphs is derived using the ([^.]+)\.")
    e.pattern("centile_years",
              r"Percentages are calculated separately for 3 consecutive years \(([\d, ]+)\)",
              cast=int_list)

    # caption 1 = citation centiles, caption 2 = author-strength (h-index)
    caps = list(re.finditer(
        r"(\w[\w\-]*) has (\d+)% papers in the top 25% overall\.\s*"
        r"A\* papers have (\d+)%,\s*A papers have (\d+)%,\s*"
        r"B papers have (\d+)%,\s*C papers have (\d+)%",
        e.flowed))
    for name, m in zip(["citation", "author_strength"], caps):
        venue, astar, a, b, c = m.group(2), m.group(3), m.group(4), m.group(5), m.group(6)
        snippet = m.group(0)
        e._record(f"{name}_top25_venue_pct", int(venue), snippet, "regex")
        e._record(f"{name}_top25_tier_baseline_pct",
                  {"A*": int(astar), "A": int(a), "B": int(b), "C": int(c)},
                  snippet, "regex")

    # --- self-reported Google Scholar block ---
    e.label("gs_h5_index", "h5 index", cast=int)
    e.label("gs_h5_of_20th_in_category", "h5 index of 20th item in category", cast=int)
    e.label("gs_position_in_subcategory", "Position in sub-category")
    e.label("gs_subcategory_url", "Sub-category url")

    # --- program committee ---
    e.label("pc_median_hindex", "Median h-index of the members of the whole committee", cast=float)
    m = re.search(r"(\d+) of the (\d+) recognised PC members were classed as established", e.flowed)
    if m:
        e._record("pc_established_count", int(m.group(1)), m.group(0), "regex")
        e._record("pc_size", int(m.group(2)), m.group(0), "regex")
    e.pattern("pc_top3_venues",
              r"Top 3 venues where PC established researchers publish:\s*(.+?)$")
    e.pattern("wpp_position_pc",
              r"This conference was in position (\d+) for PC established researchers",
              cast=int)

    # --- area leaders (the methodology that decides "flagship") ---
    e.pattern("leaders_selection_method",
              r"20 Area Leaders were chosen by the submitters, using the following selection method:\s*(.+?)The intent and instruction",
              confidence="medium")
    e.pattern("leaders_top3_venues",
              r"Top 3 venues where the selected leaders publish:\s*(.+?)$")
    e.pattern("wpp_position_leaders",
              r"This conference was in position (\d+) for the selected leaders",
              cast=int)
    leaders = re.findall(r"([A-Z][A-Za-z.\-À-ſ' ]+?)\s*\((\d{1,3})\);", e.flowed)
    if leaders:
        e._record("area_leaders",
                  [{"name": n.strip(), "gs_hindex": int(h)} for n, h in leaders],
                  "; ".join(f"{n.strip()} ({h})" for n, h in leaders[:4]), "regex")

    # --- linked machine-readable artifacts (fetch these directly) ---
    urls = re.findall(r"https://portal\.core\.edu\.au/core/media/\S+?\.txt", e.full)
    if urls:
        e._record("icore_artifact_urls", sorted(set(urls)),
                  urls[0], "regex")

    # --- last 3 instances ---
    instances = []
    for blk in re.finditer(
            r"(Most Recent Year|Second Most Recent Year|Third Most Recent Year)\s*\n(.*?)(?=Second Most Recent Year|Third Most Recent Year|^Summary)",
            e.full, re.M | re.S):
        body = blk.group(2)
        inst = {"slot": blk.group(1)}
        for k, lbl, cast in [("year", "Year", int), ("location", "Location", str),
                             ("papers_submitted", "Papers submitted", int),
                             ("papers_published", "Papers published", int)]:
            mm = re.search(rf"^\s*{lbl}\s*:\s*(.+?)\s*$", body, re.M)
            if mm:
                try:
                    inst[k] = cast(mm.group(1))
                except ValueError:
                    pass
        mm = re.search(r"^\s*Acceptance rate\s*:\s*(\d+)\s*%", body, re.M)
        if mm:
            inst["acceptance_rate_pct"] = int(mm.group(1))
        instances.append(inst)
    if instances:
        e._record("last_instances", instances, "Most Recent Year", "regex")

    # --- free-text argument sections (LLM territory for CODING, not capture) ---
    e.section("relationship_to_similar_conferences",
              "Relationship to similar conferences", "Flagship area of this conference")
    e.section("flagship_area_claim",
              "Flagship area of this conference", "Other Information")
    e.pattern("other_relevant_info",
              r"Other relevant information:\s*(.+?)(?=Attachments)")

    # --- decision documents ---
    # CONFIRMED against real 2026-round Decision PDFs (2026-09-07): "Decision"
    # is a standalone heading, the actual verdict is the line right after it
    # (e.g. "Conference to be ranked/tagged as B"), then a blank line and a
    # "Justification" heading. The original guess here ("Decision: X" on one
    # line) never matched anything real. Older rounds (e.g. CORE2023) don't
    # reliably use this heading at all — that's expected, SPEC.md §6.4 rule 2
    # routes those through the legacy LLM fallback instead.
    if link_type == "decision":
        e.pattern("outcome_verbatim", r"^Decision\s*\n([^\n]+)")
        verbatim = e.fields.get("outcome_verbatim")
        if verbatim:
            m = re.search(r"\bas\s+(A\*|Australasian B|A|B|C)\b", verbatim)
            if m:
                e._record("outcome", m.group(1), verbatim, "regex")

    fields = dict(e.fields)
    fields["core_id"] = core_id
    fields["round"] = round_
    fields["link_type"] = link_type
    fields["doc_url"] = doc_url

    return {
        "source_pdf": Path(pdf_path).name,
        "pages": len(pages),
        "needs_ocr": False,
        "fields": fields,
        "extra_fields": extra,
        "dropped_fields": e.dropped,
        "provenance": e.provenance,
    }


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Deterministic field extraction from an ICORE "
                     "submission PDF (regex-only, no LLM/OCR).")
    parser.add_argument(
        "pdf_path", type=Path,
        help="Path to the ICORE Data/Decision PDF to extract.")
    parser.add_argument("--core-id", default=None,
                         help="ICORE core_id this document belongs to.")
    parser.add_argument("--round", dest="round_", default=None, metavar="ROUND",
                         help="Ranking round, e.g. CORE2023 or ICORE2026.")
    parser.add_argument("--link-type", choices=["data", "decision"],
                         default=None, help="Document type.")
    parser.add_argument("--doc-url", default=None,
                         help="Source URL the PDF was downloaded from.")
    parser.add_argument("--doc-index", type=int, default=1,
                         help="1-based index among documents of this type "
                              "for this core_id/round (for output filename).")
    parser.add_argument("--out-dir", type=Path, default=Path("extracted"),
                         help="Directory for extracted/{core_id}_{round}_{n}.json "
                              "(only written when --core-id and --round are given).")
    args = parser.parse_args(argv)

    if not args.pdf_path.exists():
        parser.error(f"file not found: {args.pdf_path}")
    if not args.pdf_path.is_file():
        parser.error(f"not a file: {args.pdf_path}")
    if args.pdf_path.suffix.lower() != ".pdf":
        parser.error(f"expected a .pdf file, got: {args.pdf_path}")
    if args.pdf_path.stat().st_size == 0:
        parser.error(f"file is empty: {args.pdf_path}")

    return args


def main(argv=None):
    args = parse_args(argv)

    try:
        result = extract(args.pdf_path, core_id=args.core_id,
                          round_=args.round_, link_type=args.link_type,
                          doc_url=args.doc_url)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if result["needs_ocr"]:
        print(f"needs_ocr: only {result['pages']} page(s) and under "
              f"{MIN_TEXT_CHARS} chars of text extracted; skipping "
              "extraction.", file=sys.stderr)
        print(json.dumps({"needs_ocr": True}, indent=2))
        return 0

    try:
        doc = DocumentExtraction(**result["fields"],
                                  provenance=result["provenance"])
    except ValidationError as exc:
        print(f"error: extraction failed schema validation:\n{exc}",
              file=sys.stderr)
        return 1

    payload = doc.model_dump(exclude_none=False)
    if result["extra_fields"]:
        payload["extra_fields"] = result["extra_fields"]

    if args.core_id and args.round_:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        # link_type in the filename: a data doc and a decision doc for the
        # same core_id/round both default to doc_index=1 and would
        # otherwise collide (see stage2b_docs.py's batch driver for the
        # same fix — this standalone CLI path had the identical bug).
        link_type_part = args.link_type or "doc"
        out_path = args.out_dir / \
            f"{args.core_id}_{args.round_}_{link_type_part}_{args.doc_index}.json"
        out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False))
        print(f"wrote {out_path}", file=sys.stderr)
    else:
        print(json.dumps(payload, indent=2, ensure_ascii=False))

    n_fields = sum(1 for k, v in payload.items()
                   if k not in ("provenance",) and v not in (None, [], {}))
    print(f"\n--- {n_fields} fields extracted from "
          f"{result['pages']} pages ---", file=sys.stderr)
    if result["dropped_fields"]:
        print(f"dropped (no page-level provenance found): "
              f"{result['dropped_fields']}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
